name: Render paper with Nix and Quarto

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
    
permissions:
  contents: write
  
jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }} # Use the default GITHUB_TOKEN for authentication

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        logger: pretty
        log-directives: nix_installer=trace
        backtrace: full

    - name: Nix cache
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build development environment
      run: |
        nix-build

    - name: Quarto Render paper
      run: |
        nix-shell --run "quarto render _manuscript/L2_VWP_webcam_ET.qmd"

    - name: Upload rendered paper
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Rendered manuscript"
        git push origin main
